### ISSUE TITLE
1.8.5 Typing Issue

### ISSUE THREAD

**Issue by altaudio** [hyparam/hyparquet#66]
Hey team 👋

First off thanks for all the work on the project! We're using it in our team and it's great.

We hit an issue when upgrading to 1.8.5 and I think I may know why, and wanted to raise it with you.

We have code similar to the following:

```typescript
        const { parquetRead } = await import("hyparquet");
        parquetRead({
          file: // some file,
          onComplete: (raw) => {
            let data = raw.map((d) => console.log(d);
        });
```

When we do a typecheck with tsc we get the following error:

```
Error: src/component.tsx(47,24): error TS7006: Parameter 'raw' implicitly has an 'any' type.
Error: src/component.tsx(49,33): error TS7006: Parameter 'd' implicitly has an 'any' type.
```

After a quick investigation I suspect the problem is in this commit: https://github.com/hyparam/hyparquet/commit/e590f4ee03263460a389bdd29678015727cdcd5a

In particular simplifying the relative import paths from `../src/types.dts` -> `./types.dts`. This works fine in your code in the repo, but the built package moves the types out of the `src` directory and into the `types` directory, meaning the `./types.dts` reference doesn't work anymore.

Here's a screenshot of the built folder structure.
![Image](https://github.com/user-attachments/assets/904cf03b-b776-42e7-afdc-76902a27fecc)

The problem we were seeing was:
```typescript
// node_modules/.pnpm/hyparquet@1.8.4/node_modules/hyparquet/types/read.d.ts

// Trying to import from ./types.d.ts but the file is actually in ../src/types.d.ts
import type { ParquetReadOptions } from './types.d.ts'; 
```

Perhaps it's an issue with our setup, but wanted to raise anyway!

**Comment by altaudio** [comment]
@platypii No worries at all - thanks for the quick fix! 🙏🚀
